battery_manager:
  low_power_margin_ch1: 7.0
  high_power_margin_ch1: 9.0 
  low_power_margin_ch2: 7.0
  high_power_margin_ch2: 9.0
  nominal_power: 7.5
  conversion_factor: 3.0
  alarm_period: 10.0
  max_alarms: 3
