battery_manager:
  low_power_margin_ch1: 7.0
  high_power_margin_ch1: 8.0 
  low_power_margin_ch2: 7.0
  high_power_margin_ch2: 8.0
  nominal_power: 7.5
  conversion_factor: 3.0
  alarm_period: 60.0
  max_alarms: 3
